//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEscolaEntities : DbContext
    {
        public dbEscolaEntities()
            : base("name=dbEscolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAluno> tbAluno { get; set; }
        public virtual DbSet<tbProfessor> tbProfessor { get; set; }
        public virtual DbSet<tbAlunoProfessor> tbAlunoProfessor { get; set; }
    }
}
