//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlunoProfessor
    {
        public int cdAlunoProfessor { get; set; }
        public Nullable<int> cdAluno { get; set; }
        public Nullable<int> cdProfessor { get; set; }
    
        public virtual tbAluno tbAluno { get; set; }
        public virtual tbProfessor tbProfessor { get; set; }
    }
}
