//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfessor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProfessor()
        {
            this.tbAlunoProfessor = new HashSet<tbAlunoProfessor>();
        }
    
        public int cdProfessor { get; set; }
        public string nmProfessor { get; set; }
        public string nmMateria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAlunoProfessor> tbAlunoProfessor { get; set; }
    }
}
